### ISSUE TITLE
Finish title scroll

### ISSUE THREAD

**Issue by Apexal** [Apexal/wrathskeller#11]
**Is your feature request related to a problem? Please describe.**
I started to implement a wall of text that slowly scrolls before you get to the main menu screen, kind of like the start of Star Wars movies. It automatically goes to the menu when done, or if any mouse or keyboard button is clicked. However, there are 3 main issues right now:

- [x] the UI doesn't scale when you resize the window to different shapes
- [x] the font is too large
- [x] the text itself is not finished!

**Additional context**
To solve these issues, you will need to read the following resources:
- https://docs.godotengine.org/en/stable/tutorials/ui/index.html
- https://docs.godotengine.org/en/stable/tutorials/ui/gui_skinning.html

For the text itself, it should be a short background story about Shirley calling together the tournament that the game represents. Have it include some background lore and funny RPI stuff and you're good! Feel free to ask everyone for assistance.

## Make sure you work on the `title_scroll` branch instead of master: `git checkout title_scroll && git pull origin title_scroll`. You don't have to make another branch for this.

**Comment by V-aleria** [comment]
Title scroll is done and working now :)
