### ISSUE TITLE
Controls and Game Mechanics 

### ISSUE THREAD

**Issue by BianoBonzo** [Apexal/wrathskeller#13]
**Is your feature request related to a problem? Please describe.**
I started writing documentation for the controls and the main mechanics for the game. There is 1 button on the controller I'm leaving open to ideas/discussion for now. Otherwise, I've added documentation for two simple mechanics that every character will have. 

**Additional context**
We discussed how the main 4 face buttons of the controller correspond to light/heavy attacks. If people have other ideas for what the bumpers (L1, R1) and triggers (L2, R2) can do, or if you guys have ideas for other mechanics, leave a comment or let me know.

**Comment by Apexal** [comment]
1. What control should be jump?
2. Should there be directional moves like Up+Light Attack?

**Comment by BianoBonzo** [comment]
Essentially, you jump by pushing Up on the D-Pad, or moving your left joystick upwards. You can jump forward or backward by moving your left joystick diagonally upwards in the direction you want. For D-pad, you would also hold left/right. 
There are directional moves for both Up and Down. Up+Light Punch would essentially be a jumping Light Punch. I also have documentation for a player moveset, basic moves that every character has, that shows all the directional moves.
