### ISSUE TITLE
Simple Title Easter Egg

### ISSUE THREAD

**Issue by Tevetron** [Apexal/wrathskeller#15]
I do remember that the topic of Easter Eggs is often brought up. Since a we're grabbing a lot of the title screen features from Minecraft I feel it would be appropriate to include an Easter Egg similar to the one that they have implemented. There currently is a 1 in 10,000 chance for the title screen to display "Minceraft" instead of "Minecraft. I believe that we could include something similar.

![image](https://user-images.githubusercontent.com/91245066/153671194-4a20947b-e7e7-48bf-a4cc-676b77e2da26.png)

**Comment by alexisvh** [comment]
I've written the code for choosing when to display the Easter Egg title and I'm testing it locally, any ideas on what it should be?

Some suggestions:
Wrathsmeller
Wrathsekller
Wrashketller
Wrathmueller

but I feel like we can do better than these maybe?

**Comment by Apexal** [comment]
Great suggestions! Let's go with a hardcoded list of typos that it randomly selects from.

**Comment by V-aleria** [comment]
Another suggestion for the list: Wrathkutler as in prof Cutler

**Comment by alexisvh** [comment]
Cool, thanks! :)
