### ISSUE TITLE
PS4 Controller Compatibility 

### ISSUE THREAD

**Issue by BianoBonzo** [Apexal/wrathskeller#18]
Since the controls are based off of PS4 controls, the game needs to be able to be played with an actual PS4 controller for testing purposes. 

**Describe the solution you'd like**
I have a PS4 controller in my dorm, so I can use it to figure out how we can make the game compatible with a PS4 controller. The controller can be used for testing later on as well, as more mechanics gets programmed into the game.

**Comment by Apexal** [comment]
Godot makes this super easy! https://docs.godotengine.org/en/stable/tutorials/inputs/controllers_gamepads_joysticks.html

**Comment by taliyos** [comment]
Should we aim to have the game playable with any controller that can be connected to a computer (windows or mac machine)? I have a Nintendo Switch controller that we can test with.

**Comment by Apexal** [comment]
> Should we aim to have the game playable with any controller that can be connected to a computer (windows or mac machine)? I have a Nintendo Switch controller that we can test with.

As far as I can tell, it should be very simple to do so, so why not!

**Comment by Apexal** [comment]
@BianoBonzo how goes this? do the general controls support all the desired game controllers yet?

**Comment by BianoBonzo** [comment]
I think we can close this issue
