### ISSUE TITLE
Knockback X-Axis

### ISSUE THREAD

**Issue by taliyos** [Apexal/wrathskeller#41]
The character knockback does not work as intended when the hit character is on the ground. This is likely because of how velocity is handled inside the actors class.

Take a look at the character actors class. In _determine_movement() the velocity is being directly modified every frame.

So, when you take damage:

[FRAME 0]
1. velocity = player movement <- as decided by the player
 ^ Before the body has been hit
2. velocity = knockback <- player hit, velocity is overwritten
3. move_and_slide()

[FRAME 1]
1. velocity = player movement
2. The player is not hit again
3. move_and_slide()

The frame after the hit, the velocity of the character is reset to match the input. This doesn't affect the y axis because the _determine_movement() will only set _velocity.x to 0 when it's not pressed. Additionally, the knockback works on the x-axis in mid-air because of the is_on_floor() condition inside _determine_movement.

In addition to this, there could be a compounded issue with friction.

One possible solution is to separate the knockback velocity from the movement velocity and only combine them when they're set in move_and_slide().

This also brings up the question of if the player should be able to move while in knockback.

**Comment by Apexal** [comment]
Perhaps we can add a "knockback" move state that resets to "idle" after a short time.

**Comment by Apexal** [comment]
This was fixed by implementing the HURT move state, which cannot be interrupted and lasts for a constant number of seconds (0.5 for example). PR coming.
